// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcwxgroupmembers.proto

// 定义包名

package grpcwxgroupmembers

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 定义 SelectGroupMembersOrm 消息结构
type SelectGroupMembersOrm struct {
	// 类型 字段 = 标识号
	GroupIdIn            []string `protobuf:"bytes,1,rep,name=GroupIdIn,proto3" json:"GroupIdIn,omitempty"`
	WxidIn               []string `protobuf:"bytes,2,rep,name=WxidIn,proto3" json:"WxidIn,omitempty"`
	Select               string   `protobuf:"bytes,3,opt,name=Select,proto3" json:"Select,omitempty"`
	WhereStatus          string   `protobuf:"bytes,4,opt,name=WhereStatus,proto3" json:"WhereStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectGroupMembersOrm) Reset()         { *m = SelectGroupMembersOrm{} }
func (m *SelectGroupMembersOrm) String() string { return proto.CompactTextString(m) }
func (*SelectGroupMembersOrm) ProtoMessage()    {}
func (*SelectGroupMembersOrm) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{0}
}

func (m *SelectGroupMembersOrm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectGroupMembersOrm.Unmarshal(m, b)
}
func (m *SelectGroupMembersOrm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectGroupMembersOrm.Marshal(b, m, deterministic)
}
func (m *SelectGroupMembersOrm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectGroupMembersOrm.Merge(m, src)
}
func (m *SelectGroupMembersOrm) XXX_Size() int {
	return xxx_messageInfo_SelectGroupMembersOrm.Size(m)
}
func (m *SelectGroupMembersOrm) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectGroupMembersOrm.DiscardUnknown(m)
}

var xxx_messageInfo_SelectGroupMembersOrm proto.InternalMessageInfo

func (m *SelectGroupMembersOrm) GetGroupIdIn() []string {
	if m != nil {
		return m.GroupIdIn
	}
	return nil
}

func (m *SelectGroupMembersOrm) GetWxidIn() []string {
	if m != nil {
		return m.WxidIn
	}
	return nil
}

func (m *SelectGroupMembersOrm) GetSelect() string {
	if m != nil {
		return m.Select
	}
	return ""
}

func (m *SelectGroupMembersOrm) GetWhereStatus() string {
	if m != nil {
		return m.WhereStatus
	}
	return ""
}

type SelectGroupIdsOrm struct {
	// 类型 字段 = 标识号
	WxidIn               []string `protobuf:"bytes,2,rep,name=WxidIn,proto3" json:"WxidIn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectGroupIdsOrm) Reset()         { *m = SelectGroupIdsOrm{} }
func (m *SelectGroupIdsOrm) String() string { return proto.CompactTextString(m) }
func (*SelectGroupIdsOrm) ProtoMessage()    {}
func (*SelectGroupIdsOrm) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{1}
}

func (m *SelectGroupIdsOrm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectGroupIdsOrm.Unmarshal(m, b)
}
func (m *SelectGroupIdsOrm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectGroupIdsOrm.Marshal(b, m, deterministic)
}
func (m *SelectGroupIdsOrm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectGroupIdsOrm.Merge(m, src)
}
func (m *SelectGroupIdsOrm) XXX_Size() int {
	return xxx_messageInfo_SelectGroupIdsOrm.Size(m)
}
func (m *SelectGroupIdsOrm) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectGroupIdsOrm.DiscardUnknown(m)
}

var xxx_messageInfo_SelectGroupIdsOrm proto.InternalMessageInfo

func (m *SelectGroupIdsOrm) GetWxidIn() []string {
	if m != nil {
		return m.WxidIn
	}
	return nil
}

type UpdateGroupMembersOrm struct {
	GroupMemberSlice     []*UpdateGroupMembersWithField `protobuf:"bytes,1,rep,name=GroupMemberSlice,proto3" json:"GroupMemberSlice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *UpdateGroupMembersOrm) Reset()         { *m = UpdateGroupMembersOrm{} }
func (m *UpdateGroupMembersOrm) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupMembersOrm) ProtoMessage()    {}
func (*UpdateGroupMembersOrm) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{2}
}

func (m *UpdateGroupMembersOrm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupMembersOrm.Unmarshal(m, b)
}
func (m *UpdateGroupMembersOrm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupMembersOrm.Marshal(b, m, deterministic)
}
func (m *UpdateGroupMembersOrm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupMembersOrm.Merge(m, src)
}
func (m *UpdateGroupMembersOrm) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupMembersOrm.Size(m)
}
func (m *UpdateGroupMembersOrm) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupMembersOrm.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupMembersOrm proto.InternalMessageInfo

func (m *UpdateGroupMembersOrm) GetGroupMemberSlice() []*UpdateGroupMembersWithField {
	if m != nil {
		return m.GroupMemberSlice
	}
	return nil
}

type UpdateGroupMembersWithField struct {
	TableGroupMember     *TableGroupMembers `protobuf:"bytes,1,opt,name=TableGroupMember,proto3" json:"TableGroupMember,omitempty"`
	UpdateFieldSlice     []string           `protobuf:"bytes,2,rep,name=UpdateFieldSlice,proto3" json:"UpdateFieldSlice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateGroupMembersWithField) Reset()         { *m = UpdateGroupMembersWithField{} }
func (m *UpdateGroupMembersWithField) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupMembersWithField) ProtoMessage()    {}
func (*UpdateGroupMembersWithField) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{3}
}

func (m *UpdateGroupMembersWithField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupMembersWithField.Unmarshal(m, b)
}
func (m *UpdateGroupMembersWithField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupMembersWithField.Marshal(b, m, deterministic)
}
func (m *UpdateGroupMembersWithField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupMembersWithField.Merge(m, src)
}
func (m *UpdateGroupMembersWithField) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupMembersWithField.Size(m)
}
func (m *UpdateGroupMembersWithField) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupMembersWithField.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupMembersWithField proto.InternalMessageInfo

func (m *UpdateGroupMembersWithField) GetTableGroupMember() *TableGroupMembers {
	if m != nil {
		return m.TableGroupMember
	}
	return nil
}

func (m *UpdateGroupMembersWithField) GetUpdateFieldSlice() []string {
	if m != nil {
		return m.UpdateFieldSlice
	}
	return nil
}

type InsertGroupMembersOrm struct {
	GroupMemberSlice     []*TableGroupMembers `protobuf:"bytes,1,rep,name=GroupMemberSlice,proto3" json:"GroupMemberSlice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InsertGroupMembersOrm) Reset()         { *m = InsertGroupMembersOrm{} }
func (m *InsertGroupMembersOrm) String() string { return proto.CompactTextString(m) }
func (*InsertGroupMembersOrm) ProtoMessage()    {}
func (*InsertGroupMembersOrm) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{4}
}

func (m *InsertGroupMembersOrm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertGroupMembersOrm.Unmarshal(m, b)
}
func (m *InsertGroupMembersOrm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertGroupMembersOrm.Marshal(b, m, deterministic)
}
func (m *InsertGroupMembersOrm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertGroupMembersOrm.Merge(m, src)
}
func (m *InsertGroupMembersOrm) XXX_Size() int {
	return xxx_messageInfo_InsertGroupMembersOrm.Size(m)
}
func (m *InsertGroupMembersOrm) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertGroupMembersOrm.DiscardUnknown(m)
}

var xxx_messageInfo_InsertGroupMembersOrm proto.InternalMessageInfo

func (m *InsertGroupMembersOrm) GetGroupMemberSlice() []*TableGroupMembers {
	if m != nil {
		return m.GroupMemberSlice
	}
	return nil
}

type DeleteGroupContactOrm struct {
	Wxid                 string   `protobuf:"bytes,1,opt,name=Wxid,proto3" json:"Wxid,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupContactOrm) Reset()         { *m = DeleteGroupContactOrm{} }
func (m *DeleteGroupContactOrm) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupContactOrm) ProtoMessage()    {}
func (*DeleteGroupContactOrm) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{5}
}

func (m *DeleteGroupContactOrm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupContactOrm.Unmarshal(m, b)
}
func (m *DeleteGroupContactOrm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupContactOrm.Marshal(b, m, deterministic)
}
func (m *DeleteGroupContactOrm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupContactOrm.Merge(m, src)
}
func (m *DeleteGroupContactOrm) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupContactOrm.Size(m)
}
func (m *DeleteGroupContactOrm) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupContactOrm.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupContactOrm proto.InternalMessageInfo

func (m *DeleteGroupContactOrm) GetWxid() string {
	if m != nil {
		return m.Wxid
	}
	return ""
}

func (m *DeleteGroupContactOrm) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type InsertGroupContactOrm struct {
	Wxid                 string   `protobuf:"bytes,1,opt,name=Wxid,proto3" json:"Wxid,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertGroupContactOrm) Reset()         { *m = InsertGroupContactOrm{} }
func (m *InsertGroupContactOrm) String() string { return proto.CompactTextString(m) }
func (*InsertGroupContactOrm) ProtoMessage()    {}
func (*InsertGroupContactOrm) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{6}
}

func (m *InsertGroupContactOrm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertGroupContactOrm.Unmarshal(m, b)
}
func (m *InsertGroupContactOrm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertGroupContactOrm.Marshal(b, m, deterministic)
}
func (m *InsertGroupContactOrm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertGroupContactOrm.Merge(m, src)
}
func (m *InsertGroupContactOrm) XXX_Size() int {
	return xxx_messageInfo_InsertGroupContactOrm.Size(m)
}
func (m *InsertGroupContactOrm) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertGroupContactOrm.DiscardUnknown(m)
}

var xxx_messageInfo_InsertGroupContactOrm proto.InternalMessageInfo

func (m *InsertGroupContactOrm) GetWxid() string {
	if m != nil {
		return m.Wxid
	}
	return ""
}

func (m *InsertGroupContactOrm) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type SelectGroupMembersRes struct {
	GroupMemberSlice     []*TableGroupMembers `protobuf:"bytes,2,rep,name=groupMemberSlice,proto3" json:"groupMemberSlice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SelectGroupMembersRes) Reset()         { *m = SelectGroupMembersRes{} }
func (m *SelectGroupMembersRes) String() string { return proto.CompactTextString(m) }
func (*SelectGroupMembersRes) ProtoMessage()    {}
func (*SelectGroupMembersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{7}
}

func (m *SelectGroupMembersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectGroupMembersRes.Unmarshal(m, b)
}
func (m *SelectGroupMembersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectGroupMembersRes.Marshal(b, m, deterministic)
}
func (m *SelectGroupMembersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectGroupMembersRes.Merge(m, src)
}
func (m *SelectGroupMembersRes) XXX_Size() int {
	return xxx_messageInfo_SelectGroupMembersRes.Size(m)
}
func (m *SelectGroupMembersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectGroupMembersRes.DiscardUnknown(m)
}

var xxx_messageInfo_SelectGroupMembersRes proto.InternalMessageInfo

func (m *SelectGroupMembersRes) GetGroupMemberSlice() []*TableGroupMembers {
	if m != nil {
		return m.GroupMemberSlice
	}
	return nil
}

type SelectGroupIdsRes struct {
	GroupIdSlice         []string `protobuf:"bytes,2,rep,name=groupIdSlice,proto3" json:"groupIdSlice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectGroupIdsRes) Reset()         { *m = SelectGroupIdsRes{} }
func (m *SelectGroupIdsRes) String() string { return proto.CompactTextString(m) }
func (*SelectGroupIdsRes) ProtoMessage()    {}
func (*SelectGroupIdsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{8}
}

func (m *SelectGroupIdsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectGroupIdsRes.Unmarshal(m, b)
}
func (m *SelectGroupIdsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectGroupIdsRes.Marshal(b, m, deterministic)
}
func (m *SelectGroupIdsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectGroupIdsRes.Merge(m, src)
}
func (m *SelectGroupIdsRes) XXX_Size() int {
	return xxx_messageInfo_SelectGroupIdsRes.Size(m)
}
func (m *SelectGroupIdsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectGroupIdsRes.DiscardUnknown(m)
}

var xxx_messageInfo_SelectGroupIdsRes proto.InternalMessageInfo

func (m *SelectGroupIdsRes) GetGroupIdSlice() []string {
	if m != nil {
		return m.GroupIdSlice
	}
	return nil
}

type UpdateGroupMembersRes struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupMembersRes) Reset()         { *m = UpdateGroupMembersRes{} }
func (m *UpdateGroupMembersRes) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupMembersRes) ProtoMessage()    {}
func (*UpdateGroupMembersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{9}
}

func (m *UpdateGroupMembersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupMembersRes.Unmarshal(m, b)
}
func (m *UpdateGroupMembersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupMembersRes.Marshal(b, m, deterministic)
}
func (m *UpdateGroupMembersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupMembersRes.Merge(m, src)
}
func (m *UpdateGroupMembersRes) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupMembersRes.Size(m)
}
func (m *UpdateGroupMembersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupMembersRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupMembersRes proto.InternalMessageInfo

func (m *UpdateGroupMembersRes) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type InsertGroupMembersRes struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertGroupMembersRes) Reset()         { *m = InsertGroupMembersRes{} }
func (m *InsertGroupMembersRes) String() string { return proto.CompactTextString(m) }
func (*InsertGroupMembersRes) ProtoMessage()    {}
func (*InsertGroupMembersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{10}
}

func (m *InsertGroupMembersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertGroupMembersRes.Unmarshal(m, b)
}
func (m *InsertGroupMembersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertGroupMembersRes.Marshal(b, m, deterministic)
}
func (m *InsertGroupMembersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertGroupMembersRes.Merge(m, src)
}
func (m *InsertGroupMembersRes) XXX_Size() int {
	return xxx_messageInfo_InsertGroupMembersRes.Size(m)
}
func (m *InsertGroupMembersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertGroupMembersRes.DiscardUnknown(m)
}

var xxx_messageInfo_InsertGroupMembersRes proto.InternalMessageInfo

func (m *InsertGroupMembersRes) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type DeleteGroupContactRes struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupContactRes) Reset()         { *m = DeleteGroupContactRes{} }
func (m *DeleteGroupContactRes) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupContactRes) ProtoMessage()    {}
func (*DeleteGroupContactRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{11}
}

func (m *DeleteGroupContactRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupContactRes.Unmarshal(m, b)
}
func (m *DeleteGroupContactRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupContactRes.Marshal(b, m, deterministic)
}
func (m *DeleteGroupContactRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupContactRes.Merge(m, src)
}
func (m *DeleteGroupContactRes) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupContactRes.Size(m)
}
func (m *DeleteGroupContactRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupContactRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupContactRes proto.InternalMessageInfo

func (m *DeleteGroupContactRes) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type InsertGroupContactRes struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertGroupContactRes) Reset()         { *m = InsertGroupContactRes{} }
func (m *InsertGroupContactRes) String() string { return proto.CompactTextString(m) }
func (*InsertGroupContactRes) ProtoMessage()    {}
func (*InsertGroupContactRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{12}
}

func (m *InsertGroupContactRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertGroupContactRes.Unmarshal(m, b)
}
func (m *InsertGroupContactRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertGroupContactRes.Marshal(b, m, deterministic)
}
func (m *InsertGroupContactRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertGroupContactRes.Merge(m, src)
}
func (m *InsertGroupContactRes) XXX_Size() int {
	return xxx_messageInfo_InsertGroupContactRes.Size(m)
}
func (m *InsertGroupContactRes) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertGroupContactRes.DiscardUnknown(m)
}

var xxx_messageInfo_InsertGroupContactRes proto.InternalMessageInfo

func (m *InsertGroupContactRes) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type UpdateTableGroupMembers struct {
	GroupMembers         *TableGroupMembers `protobuf:"bytes,1,opt,name=GroupMembers,proto3" json:"GroupMembers,omitempty"`
	UpdateFields         []string           `protobuf:"bytes,2,rep,name=UpdateFields,proto3" json:"UpdateFields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateTableGroupMembers) Reset()         { *m = UpdateTableGroupMembers{} }
func (m *UpdateTableGroupMembers) String() string { return proto.CompactTextString(m) }
func (*UpdateTableGroupMembers) ProtoMessage()    {}
func (*UpdateTableGroupMembers) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{13}
}

func (m *UpdateTableGroupMembers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTableGroupMembers.Unmarshal(m, b)
}
func (m *UpdateTableGroupMembers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTableGroupMembers.Marshal(b, m, deterministic)
}
func (m *UpdateTableGroupMembers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTableGroupMembers.Merge(m, src)
}
func (m *UpdateTableGroupMembers) XXX_Size() int {
	return xxx_messageInfo_UpdateTableGroupMembers.Size(m)
}
func (m *UpdateTableGroupMembers) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTableGroupMembers.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTableGroupMembers proto.InternalMessageInfo

func (m *UpdateTableGroupMembers) GetGroupMembers() *TableGroupMembers {
	if m != nil {
		return m.GroupMembers
	}
	return nil
}

func (m *UpdateTableGroupMembers) GetUpdateFields() []string {
	if m != nil {
		return m.UpdateFields
	}
	return nil
}

type TableGroupMembers struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	Wxid                 string   `protobuf:"bytes,2,opt,name=Wxid,proto3" json:"Wxid,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	CreateTime           int64    `protobuf:"varint,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	Flag                 int64    `protobuf:"varint,5,opt,name=Flag,proto3" json:"Flag,omitempty"`
	Status               int64    `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableGroupMembers) Reset()         { *m = TableGroupMembers{} }
func (m *TableGroupMembers) String() string { return proto.CompactTextString(m) }
func (*TableGroupMembers) ProtoMessage()    {}
func (*TableGroupMembers) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b77da89bba893c, []int{14}
}

func (m *TableGroupMembers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableGroupMembers.Unmarshal(m, b)
}
func (m *TableGroupMembers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableGroupMembers.Marshal(b, m, deterministic)
}
func (m *TableGroupMembers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableGroupMembers.Merge(m, src)
}
func (m *TableGroupMembers) XXX_Size() int {
	return xxx_messageInfo_TableGroupMembers.Size(m)
}
func (m *TableGroupMembers) XXX_DiscardUnknown() {
	xxx_messageInfo_TableGroupMembers.DiscardUnknown(m)
}

var xxx_messageInfo_TableGroupMembers proto.InternalMessageInfo

func (m *TableGroupMembers) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *TableGroupMembers) GetWxid() string {
	if m != nil {
		return m.Wxid
	}
	return ""
}

func (m *TableGroupMembers) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *TableGroupMembers) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *TableGroupMembers) GetFlag() int64 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *TableGroupMembers) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*SelectGroupMembersOrm)(nil), "grpcwxgroupmembers.SelectGroupMembersOrm")
	proto.RegisterType((*SelectGroupIdsOrm)(nil), "grpcwxgroupmembers.SelectGroupIdsOrm")
	proto.RegisterType((*UpdateGroupMembersOrm)(nil), "grpcwxgroupmembers.UpdateGroupMembersOrm")
	proto.RegisterType((*UpdateGroupMembersWithField)(nil), "grpcwxgroupmembers.UpdateGroupMembersWithField")
	proto.RegisterType((*InsertGroupMembersOrm)(nil), "grpcwxgroupmembers.InsertGroupMembersOrm")
	proto.RegisterType((*DeleteGroupContactOrm)(nil), "grpcwxgroupmembers.DeleteGroupContactOrm")
	proto.RegisterType((*InsertGroupContactOrm)(nil), "grpcwxgroupmembers.InsertGroupContactOrm")
	proto.RegisterType((*SelectGroupMembersRes)(nil), "grpcwxgroupmembers.SelectGroupMembersRes")
	proto.RegisterType((*SelectGroupIdsRes)(nil), "grpcwxgroupmembers.SelectGroupIdsRes")
	proto.RegisterType((*UpdateGroupMembersRes)(nil), "grpcwxgroupmembers.UpdateGroupMembersRes")
	proto.RegisterType((*InsertGroupMembersRes)(nil), "grpcwxgroupmembers.InsertGroupMembersRes")
	proto.RegisterType((*DeleteGroupContactRes)(nil), "grpcwxgroupmembers.DeleteGroupContactRes")
	proto.RegisterType((*InsertGroupContactRes)(nil), "grpcwxgroupmembers.InsertGroupContactRes")
	proto.RegisterType((*UpdateTableGroupMembers)(nil), "grpcwxgroupmembers.UpdateTableGroupMembers")
	proto.RegisterType((*TableGroupMembers)(nil), "grpcwxgroupmembers.TableGroupMembers")
}

func init() { proto.RegisterFile("grpcwxgroupmembers.proto", fileDescriptor_50b77da89bba893c) }

var fileDescriptor_50b77da89bba893c = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xf9, 0x83, 0x4c, 0x2a, 0x94, 0x8e, 0x14, 0xb0, 0x0c, 0x42, 0xd1, 0x4a, 0x95, 0x0a,
	0x95, 0x8a, 0x14, 0x0e, 0x3c, 0x40, 0xa0, 0xc8, 0x07, 0x40, 0x71, 0x40, 0x39, 0x70, 0xc1, 0xb1,
	0x47, 0xae, 0x8b, 0x1d, 0x47, 0xb6, 0x23, 0xca, 0x13, 0xc0, 0x8d, 0x17, 0xe0, 0x05, 0x78, 0x4b,
	0xb4, 0xbb, 0x6e, 0xd8, 0x78, 0xb7, 0xa9, 0xdb, 0x9b, 0xe7, 0xdb, 0x99, 0xf9, 0xe6, 0xe7, 0xcb,
	0x28, 0x60, 0x47, 0xf9, 0x3a, 0xf8, 0x7e, 0x19, 0xe5, 0xd9, 0x66, 0x9d, 0x52, 0xba, 0xa4, 0xbc,
	0x38, 0x5d, 0xe7, 0x59, 0x99, 0x21, 0xea, 0x2f, 0xec, 0xa7, 0x05, 0xa3, 0x39, 0x25, 0x14, 0x94,
	0xef, 0x38, 0xfc, 0x5e, 0xc2, 0x1f, 0xf3, 0x14, 0x9f, 0x42, 0x5f, 0x40, 0x6e, 0xe8, 0xae, 0x6c,
	0x6b, 0xdc, 0x3e, 0xee, 0x7b, 0xff, 0x01, 0x7c, 0x04, 0xbd, 0xc5, 0x65, 0xcc, 0x9f, 0x5a, 0xe2,
	0xa9, 0xb2, 0x38, 0x2e, 0xd3, 0xd9, 0xed, 0xb1, 0xc5, 0x71, 0x69, 0xe1, 0x18, 0x06, 0x8b, 0x73,
	0xca, 0x69, 0x5e, 0xfa, 0xe5, 0xa6, 0xb0, 0x3b, 0xe2, 0x51, 0x85, 0xd8, 0x09, 0x1c, 0x2a, 0x85,
	0xb8, 0xa1, 0x28, 0xe2, 0x1a, 0x1a, 0x56, 0xc2, 0xe8, 0xf3, 0x3a, 0xf4, 0x4b, 0xaa, 0x57, 0xfd,
	0x05, 0x86, 0x0a, 0x34, 0x4f, 0xe2, 0x80, 0x44, 0xf1, 0x83, 0xc9, 0xcb, 0x53, 0xc3, 0x60, 0xf4,
	0x24, 0x8b, 0xb8, 0x3c, 0x3f, 0x8b, 0x29, 0x09, 0x3d, 0x2d, 0x11, 0xfb, 0x63, 0xc1, 0x93, 0x3d,
	0x11, 0x38, 0x83, 0xe1, 0x27, 0x7f, 0x99, 0xa8, 0xaf, 0xb6, 0x35, 0xb6, 0x8e, 0x07, 0x93, 0x23,
	0x13, 0x79, 0xdd, 0xb7, 0xf0, 0xb4, 0x70, 0x7c, 0x01, 0x43, 0xc9, 0x28, 0x18, 0x64, 0x3f, 0x72,
	0x14, 0x1a, 0xce, 0x2e, 0x60, 0xe4, 0xae, 0x0a, 0xca, 0xb5, 0x55, 0xce, 0xae, 0x1d, 0x4a, 0xd3,
	0xba, 0xb4, 0x51, 0xbc, 0x85, 0xd1, 0x1b, 0x4a, 0xa8, 0x9a, 0xc4, 0x34, 0x5b, 0x95, 0x7e, 0x50,
	0x72, 0x2e, 0x84, 0x0e, 0xdf, 0x91, 0xe8, 0xbb, 0xef, 0x89, 0x6f, 0xb4, 0xe1, 0x7e, 0xb5, 0x54,
	0xbb, 0x25, 0xe0, 0x2b, 0x93, 0xa7, 0x51, 0x4a, 0xbe, 0x73, 0x9a, 0x0b, 0x93, 0x88, 0x3d, 0x2a,
	0x78, 0xe7, 0x51, 0xbd, 0xf3, 0xd6, 0xad, 0x3a, 0xaf, 0x87, 0xb3, 0xd7, 0x75, 0x9d, 0x72, 0x1e,
	0x06, 0x07, 0x91, 0x34, 0xd5, 0x15, 0xed, 0x60, 0xec, 0xc4, 0xa4, 0x59, 0x1e, 0x8c, 0xd0, 0x99,
	0x66, 0x21, 0x89, 0x5e, 0xdb, 0x9e, 0xf8, 0xe6, 0xce, 0xfa, 0x2e, 0xf7, 0x38, 0xeb, 0xcb, 0x68,
	0x96, 0xf9, 0x06, 0xe7, 0x5f, 0x16, 0x3c, 0x96, 0x45, 0x6b, 0xa3, 0x41, 0x17, 0x0e, 0x54, 0xfb,
	0x76, 0x4a, 0xdf, 0x09, 0xe5, 0xe3, 0x53, 0xd4, 0x5c, 0x5c, 0x8d, 0x4f, 0xc5, 0xd8, 0x5f, 0x0b,
	0x0e, 0xf5, 0x22, 0x14, 0x4d, 0x58, 0x3b, 0x9a, 0xd8, 0x2a, 0xa8, 0xa5, 0x28, 0xc8, 0x81, 0x07,
	0x1f, 0xe2, 0xe0, 0xdb, 0xca, 0x4f, 0xa9, 0xba, 0x4f, 0x5b, 0x1b, 0x9f, 0x01, 0x4c, 0x73, 0xe2,
	0x9d, 0xc6, 0x29, 0x89, 0x03, 0xd5, 0xf6, 0x14, 0x84, 0xe7, 0x3b, 0x4b, 0xfc, 0xc8, 0xee, 0xca,
	0xf1, 0xf0, 0x6f, 0x71, 0xed, 0xe4, 0x41, 0xeb, 0x09, 0xb4, 0xb2, 0x26, 0xbf, 0xbb, 0xd0, 0x9d,
	0x6d, 0x28, 0xff, 0x81, 0x09, 0xa0, 0xae, 0x4c, 0x7c, 0x6e, 0x1a, 0x92, 0xf1, 0x0c, 0x3b, 0x0d,
	0x5d, 0x3d, 0x2a, 0xd8, 0x3d, 0xfc, 0x0a, 0x0f, 0x77, 0xb5, 0x89, 0x47, 0x37, 0x84, 0xcb, 0x3b,
	0xeb, 0x34, 0x70, 0x93, 0x0c, 0x09, 0xa0, 0x2e, 0x62, 0x73, 0x3f, 0xc6, 0x03, 0xed, 0x34, 0x74,
	0xdd, 0xb2, 0xe9, 0xbf, 0x02, 0x33, 0x9b, 0xf1, 0xf2, 0x39, 0x0d, 0x5d, 0xb7, 0x6c, 0xfa, 0xcf,
	0xc8, 0xcc, 0x66, 0xbc, 0x7d, 0x4e, 0x43, 0x57, 0x53, 0x6f, 0x7b, 0xd9, 0x8c, 0x27, 0xd2, 0x69,
	0xe8, 0x2a, 0xd8, 0x96, 0x3d, 0xf1, 0x17, 0xe0, 0xd5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x89,
	0x97, 0x4b, 0xe7, 0x1e, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// 返回的结构体都有一个Code的key，值为0则正常，非0就需要排查问题程序报错
	SelectGroupMembers(ctx context.Context, in *SelectGroupMembersOrm, opts ...grpc.CallOption) (*SelectGroupMembersRes, error)
	SelectGroupIds(ctx context.Context, in *SelectGroupIdsOrm, opts ...grpc.CallOption) (*SelectGroupIdsRes, error)
	UpdateGroupMembers(ctx context.Context, in *UpdateGroupMembersOrm, opts ...grpc.CallOption) (*UpdateGroupMembersRes, error)
	InsertGroupMembers(ctx context.Context, in *InsertGroupMembersOrm, opts ...grpc.CallOption) (*InsertGroupMembersRes, error)
	DeleteGroupContact(ctx context.Context, in *DeleteGroupContactOrm, opts ...grpc.CallOption) (*DeleteGroupContactRes, error)
	InsertGroupContact(ctx context.Context, in *InsertGroupContactOrm, opts ...grpc.CallOption) (*InsertGroupContactRes, error)
}

type queryClient struct {
	cc *grpc.ClientConn
}

func NewQueryClient(cc *grpc.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) SelectGroupMembers(ctx context.Context, in *SelectGroupMembersOrm, opts ...grpc.CallOption) (*SelectGroupMembersRes, error) {
	out := new(SelectGroupMembersRes)
	err := c.cc.Invoke(ctx, "/grpcwxgroupmembers.Query/SelectGroupMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SelectGroupIds(ctx context.Context, in *SelectGroupIdsOrm, opts ...grpc.CallOption) (*SelectGroupIdsRes, error) {
	out := new(SelectGroupIdsRes)
	err := c.cc.Invoke(ctx, "/grpcwxgroupmembers.Query/SelectGroupIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UpdateGroupMembers(ctx context.Context, in *UpdateGroupMembersOrm, opts ...grpc.CallOption) (*UpdateGroupMembersRes, error) {
	out := new(UpdateGroupMembersRes)
	err := c.cc.Invoke(ctx, "/grpcwxgroupmembers.Query/UpdateGroupMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) InsertGroupMembers(ctx context.Context, in *InsertGroupMembersOrm, opts ...grpc.CallOption) (*InsertGroupMembersRes, error) {
	out := new(InsertGroupMembersRes)
	err := c.cc.Invoke(ctx, "/grpcwxgroupmembers.Query/InsertGroupMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DeleteGroupContact(ctx context.Context, in *DeleteGroupContactOrm, opts ...grpc.CallOption) (*DeleteGroupContactRes, error) {
	out := new(DeleteGroupContactRes)
	err := c.cc.Invoke(ctx, "/grpcwxgroupmembers.Query/DeleteGroupContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) InsertGroupContact(ctx context.Context, in *InsertGroupContactOrm, opts ...grpc.CallOption) (*InsertGroupContactRes, error) {
	out := new(InsertGroupContactRes)
	err := c.cc.Invoke(ctx, "/grpcwxgroupmembers.Query/InsertGroupContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// 返回的结构体都有一个Code的key，值为0则正常，非0就需要排查问题程序报错
	SelectGroupMembers(context.Context, *SelectGroupMembersOrm) (*SelectGroupMembersRes, error)
	SelectGroupIds(context.Context, *SelectGroupIdsOrm) (*SelectGroupIdsRes, error)
	UpdateGroupMembers(context.Context, *UpdateGroupMembersOrm) (*UpdateGroupMembersRes, error)
	InsertGroupMembers(context.Context, *InsertGroupMembersOrm) (*InsertGroupMembersRes, error)
	DeleteGroupContact(context.Context, *DeleteGroupContactOrm) (*DeleteGroupContactRes, error)
	InsertGroupContact(context.Context, *InsertGroupContactOrm) (*InsertGroupContactRes, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) SelectGroupMembers(ctx context.Context, req *SelectGroupMembersOrm) (*SelectGroupMembersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectGroupMembers not implemented")
}
func (*UnimplementedQueryServer) SelectGroupIds(ctx context.Context, req *SelectGroupIdsOrm) (*SelectGroupIdsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectGroupIds not implemented")
}
func (*UnimplementedQueryServer) UpdateGroupMembers(ctx context.Context, req *UpdateGroupMembersOrm) (*UpdateGroupMembersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupMembers not implemented")
}
func (*UnimplementedQueryServer) InsertGroupMembers(ctx context.Context, req *InsertGroupMembersOrm) (*InsertGroupMembersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertGroupMembers not implemented")
}
func (*UnimplementedQueryServer) DeleteGroupContact(ctx context.Context, req *DeleteGroupContactOrm) (*DeleteGroupContactRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroupContact not implemented")
}
func (*UnimplementedQueryServer) InsertGroupContact(ctx context.Context, req *InsertGroupContactOrm) (*InsertGroupContactRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertGroupContact not implemented")
}

func RegisterQueryServer(s *grpc.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_SelectGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectGroupMembersOrm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SelectGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcwxgroupmembers.Query/SelectGroupMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SelectGroupMembers(ctx, req.(*SelectGroupMembersOrm))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SelectGroupIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectGroupIdsOrm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SelectGroupIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcwxgroupmembers.Query/SelectGroupIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SelectGroupIds(ctx, req.(*SelectGroupIdsOrm))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UpdateGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupMembersOrm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UpdateGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcwxgroupmembers.Query/UpdateGroupMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UpdateGroupMembers(ctx, req.(*UpdateGroupMembersOrm))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_InsertGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertGroupMembersOrm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InsertGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcwxgroupmembers.Query/InsertGroupMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InsertGroupMembers(ctx, req.(*InsertGroupMembersOrm))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DeleteGroupContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupContactOrm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DeleteGroupContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcwxgroupmembers.Query/DeleteGroupContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DeleteGroupContact(ctx, req.(*DeleteGroupContactOrm))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_InsertGroupContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertGroupContactOrm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InsertGroupContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcwxgroupmembers.Query/InsertGroupContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InsertGroupContact(ctx, req.(*InsertGroupContactOrm))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcwxgroupmembers.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectGroupMembers",
			Handler:    _Query_SelectGroupMembers_Handler,
		},
		{
			MethodName: "SelectGroupIds",
			Handler:    _Query_SelectGroupIds_Handler,
		},
		{
			MethodName: "UpdateGroupMembers",
			Handler:    _Query_UpdateGroupMembers_Handler,
		},
		{
			MethodName: "InsertGroupMembers",
			Handler:    _Query_InsertGroupMembers_Handler,
		},
		{
			MethodName: "DeleteGroupContact",
			Handler:    _Query_DeleteGroupContact_Handler,
		},
		{
			MethodName: "InsertGroupContact",
			Handler:    _Query_InsertGroupContact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcwxgroupmembers.proto",
}
